"""Persist the DUT subcircuits and one representative static deck per
testbench under ../dut/ and ../netlists/.

The static decks reference their DUT via `.include ../dut/dut_<x>.spice` and
must be run from inside netlists/ (where the required .spiceinit lives):

    cd ../netlists && ngspice -b tb_pam4_sparam_msb_1ghz.spice

Regenerate after editing driver_lib.py:  python dump_netlists.py
"""
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from driver_lib import (DUTS, DriverParams, dut_subckt, tb_ac, tb_ac_s22,
                        tb_bias, tb_eye, tb_s22, tb_sparam)

HERE = Path(__file__).parent
ROOT = HERE.parent
DUT_DIR = ROOT / "dut"
NL_DIR = ROOT / "netlists"
DUT_DIR.mkdir(exist_ok=True)
NL_DIR.mkdir(exist_ok=True)

dp = DriverParams()  # defaults == EIC-verified nominal

# Portable .spiceinit: resolved through $PDK_ROOT/$PDK (drawings convention).
SPICEINIT = (
    "* IHP SG13G2 HBT decks — REQUIRED: without ngbehavior=hsa the HBT\n"
    "* conducts 0 current (silently). Export PDK_ROOT and PDK first, e.g.\n"
    "*   export PDK_ROOT=$HOME/local/pdks   PDK=ihp-sg13g2\n"
    "setcs sourcepath = ( $sourcepath $PDK_ROOT/$PDK/libs.tech/ngspice/models )\n"
    "set ngbehavior=hsa\n"
)
(NL_DIR / ".spiceinit").write_text(SPICEINIT)
(NL_DIR / "spiceinit.txt").write_text(
    "# Copy of .spiceinit (ngspice reads the dotfile from the run directory).\n"
    + SPICEINIT)

# --- DUT subcircuits -------------------------------------------------------
for dut in DUTS:
    _, sub, _ = dut_subckt(dut, dp)
    (DUT_DIR / f"dut_{dut}.spice").write_text(sub)
    print(f"dut/dut_{dut}.spice")

decks: list[tuple[str, str, str]] = []


def inc(dut: str) -> str:
    return f".include ../dut/dut_{dut}.spice"


# --- per-DUT testbenches ---------------------------------------------------
for dut in DUTS:
    drive = "msb" if dut == "pam4" else "in"
    d, _, _ = tb_bias(dut, inc(dut), dp=dp)
    decks.append((f"tb_{dut}_bias.spice",
                  "Bias/operating point: ramp-and-hold; power + per-device V_CE.", d))
    d, _, _ = tb_sparam(dut, inc(dut), f_hz=1e9, drive=drive, dp=dp)
    decks.append((f"tb_{dut}_sparam_{drive}_1ghz.spice",
                  f"S21/S11 tone probe, {drive} driven, f=1 GHz (LF gain point); "
                  "run_verify.py sweeps 1..70 GHz.", d))
    d = tb_ac(dut, inc(dut), drive=drive, dp=dp)
    decks.append((f"tb_{dut}_op_ac.spice",
                  "Direct .op + .ac S21/S11 sweep (ngspice-45; fails on "
                  "ngspice-44, see README).", d))

# pam4 extras: LSB-driven path, S22 (tran + ac), swing, eye.
d, _, _ = tb_sparam("pam4", inc("pam4"), f_hz=1e9, drive="lsb", dp=dp)
decks.append(("tb_pam4_sparam_lsb_1ghz.spice",
              "S21/S11 tone probe, LSB driven, f=1 GHz.", d))
d = tb_ac("pam4", inc("pam4"), drive="lsb", dp=dp)
decks.append(("tb_pam4_op_ac_lsb.spice",
              "Direct .op + .ac S21/S11 sweep, LSB driven.", d))
d, _, _ = tb_s22("pam4", inc("pam4"), f_hz=50e9, dp=dp)
decks.append(("tb_pam4_s22_50ghz.spice",
              "S22 output-reflection tone probe, f=50 GHz (band edge); "
              "run_verify.py sweeps 2..50 GHz.", d))
d = tb_ac_s22("pam4", inc("pam4"), dp=dp)
decks.append(("tb_pam4_op_ac_s22.spice",
              "Direct .op + .ac S22 sweep.", d))
d, _, _ = tb_sparam("pam4", inc("pam4"), f_hz=1e9, drive="both", dp=dp,
                    vac_mv=1600, settle_periods=4, window_periods=8)
decks.append(("tb_pam4_swing_1ghz.spice",
              "Large-signal swing: LSB+MSB driven in phase, 1.6 Vpp input, "
              "1 GHz; run_verify.py sweeps 0.2..1.6 Vpp.", d))
random.seed(7)
nsym = 120
msb_bits = [random.randint(0, 1) for _ in range(nsym)]
lsb_bits = [random.randint(0, 1) for _ in range(nsym)]
d, _, _ = tb_eye(inc("pam4"), msb_bits=msb_bits, lsb_bits=lsb_bits, dp=dp)
decks.append(("tb_pam4_eye_48gbaud.spice",
              "48 GBaud PAM-4 eye: independent MSB/LSB NRZ streams (seed 7, "
              "120 symbols, 200 mV input).", d))

for name, _, deck in decks:
    (NL_DIR / name).write_text(deck)
    print(f"netlists/{name}")

# --- netlists/README.md ----------------------------------------------------
rows = "\n".join(f"| `{n}` | {desc} |" for n, desc, _ in decks)
(NL_DIR / "README.md").write_text(f"""\
# Static testbench decks — SG13G2 PAM-4 driver (3 DUTs)

Generated by `../testbenches/dump_netlists.py` at the EIC-verified nominal
point. Each deck `.include`s its DUT from `../dut/` and must run from this
directory (the `.spiceinit` here sets the model sourcepath + `ngbehavior=hsa`;
without it the HBT conducts 0 current — silently):

```
export PDK_ROOT=$HOME/local/pdks PDK=ihp-sg13g2
ngspice -b tb_pam4_sparam_msb_1ghz.spice
```

| File | Analysis |
|------|----------|
{rows}

`tb_*_op_ac*` decks need ngspice-45 (the self-heating VBIC fails .op/.ac on
ngspice-44 — see ../README.md). All other decks are ngspice-44-safe transient
ramp-from-0 probes.
""")
print("netlists/README.md")
