"""raw/ export: the deck writer, the catalog ``raw``/``schematic``
blocks, and the Tier-0 cross-ref + Tier-1 drift guards. All PDK-free — the committed decks are
actually SIMULATED on the base image in ``test_slow_sim.py`` (``test_L1_committed_raw_deck_simulates``).
"""

from __future__ import annotations

import json

import pytest

from spicexplorer_analog_db import catalog, export, model, paths
from spicexplorer_analog_db.assemble import assemble

CIRCUIT = "amp_001_5t"


@pytest.fixture(scope="module")
def ota() -> model.Circuit:
    return model.load_circuit(CIRCUIT)


# ───────────────────────────── deck rendering ─────────────────────────────


def test_render_deck_is_self_contained(ota):
    deck = export.render_deck(ota, "ac_open_loop", "sky130", "tt")
    assert deck.startswith("** GENERATED by `analog-db export-raw` — DO NOT EDIT.")
    assert "${" not in deck  # every placeholder bound
    assert deck.rstrip().endswith(".end")  # a complete deck
    assert ".subckt amp_001_5t vdd vout vinp vinn ibias vss" in deck  # DUT inlined
    assert ".ends" in deck and "ac dec" in deck  # subckt closes + the testbench control


def test_deck_body_is_exactly_the_assembler_output(ota):
    """The banner is the ONLY thing added: the netlist body is byte-for-byte ``assemble()`` minus its
    one-line provenance header — so a committed deck can never silently diverge from the resolver."""
    asm_tail = assemble(ota, "ac_open_loop", "sky130", "tt").split("\n", 1)[1]
    assert export.render_deck(ota, "ac_open_loop", "sky130", "tt").endswith(asm_tail)


@pytest.mark.corpus
def test_every_deck_control_block_ends_with_quit(generated_decks):
    """Every generated testbench deck must terminate its ``.control`` block with ``quit``.

    spicelib's ngspice runner (the optimizer's `NGSpice_Wrapper`) drives ngspice in an
    interactive control session and needs a ``quit`` to close it cleanly and hand back the
    RAW — without it the optimizer can't read the result vectors. This mirrors the reference
    optimizer testbenches (``ota-improved_tb-*.spice``), which already end ``write``/``quit``.
    Guards the invariant at the *deck* level, so a future testbench template that forgets
    ``quit`` fails here regardless of which template it came from. (The `_dut.spice` subckt
    and the `.sch` schematics carry no control block and are exempt.)"""
    offenders = []
    for rel, text in generated_decks.items():
        if not rel.endswith(".spice") or rel.endswith("/_dut.spice"):
            continue
        lines = [ln.strip().lower() for ln in text.splitlines()]
        if ".control" not in lines:
            continue
        c = lines.index(".control")
        e = lines.index(".endc", c)
        body = [ln for ln in lines[c + 1 : e] if ln]
        if "quit" not in body:
            offenders.append(rel)
    assert not offenders, f"{len(offenders)} deck(s) lack a terminating quit: {offenders[:5]}"


def test_standalone_dut_subckt(ota):
    dut = export.render_dut(ota, "sky130")
    assert dut.startswith("** GENERATED by `analog-db export-raw`")
    assert ".subckt amp_001_5t" in dut and dut.rstrip().endswith(".ends")
    assert ".param x_dut_" in dut  # sizing defaults carried at global scope
    assert "sky130_fd_pr__nfet_01v8" in dut  # lowered to the PDK device


def test_deck_filename_corner_suffix(ota):
    assert export.deck_path(ota, "ac_open_loop", "sky130", "tt").name == "ac_open_loop.spice"
    assert export.deck_path(ota, "ac_open_loop", "sky130", "ss").name == "ac_open_loop__ss.spice"


# ───────────────────────────── the pure generator ─────────────────────────────


@pytest.mark.corpus
def test_generate_all_is_deterministic(generated_decks):
    # use_cache=False so this is a genuinely fresh render, not the memoized session one
    b, _ = export.generate_all(use_cache=False)
    assert generated_decks == b and len(b) > 100


@pytest.mark.corpus
def test_generate_skips_disabled_and_unbound(ota, generated_decks):
    decks = generated_decks
    _, skipped = export.generate_all(["amp_018_telescopic_cascode", "ldo_005_buffered_ref"])
    reasons = dict(skipped)
    # a scaffolded `enabled: false` analysis is skipped with a reason, not exported
    assert reasons.get("amp_018_telescopic_cascode/linearity") == "disabled"
    assert "raw/amp_018_telescopic_cascode/ihp-sg13g2/linearity.spice" not in decks
    # an UNBOUND pdk yields no deck at all (not even an error). ldo_005_buffered_ref binds
    # ihp-sg13g2 + gf180mcu only — it has no sky130 binding. (This used to assert on
    # amp_017_tan_clia, which has bound ihp-sg13g2 since #55 and now binds all four PDKs.)
    assert "raw/ldo_005_buffered_ref/ihp-sg13g2/dc_op.spice" in decks
    assert "raw/ldo_005_buffered_ref/sky130/dc_op.spice" not in decks
    # every amp_001_5t analysis × pdk + a _dut is present
    for pdk in ota.pdks:
        assert f"raw/amp_001_5t/{pdk}/_dut.spice" in decks
        for aid in ota.analyses:
            assert f"raw/amp_001_5t/{pdk}/{aid}.spice" in decks


def test_deck_index_groups_by_pdk_and_testbench():
    idx = export.deck_index()
    sky = idx["amp_001_5t"]["sky130"]
    assert sky["ac_open_loop"] == "raw/amp_001_5t/sky130/ac_open_loop.spice"
    assert "_dut" in sky and {"ihp-sg13g2", "sky130", "gf180mcu"} <= set(idx["amp_001_5t"])  # any further registered lane may add groups


# ───────────────────────────── xschem schematic (.sch) ─────────────────────────────


def test_generate_emits_one_circuit_schematic(ota):
    """Each circuit gets a single deterministic ``<id>.sch`` at circuit level, drawn from the ref PDK."""
    pytest.importorskip("spicexplorer_netlist2xschem")
    decks, _ = export.generate_all([CIRCUIT])
    rel = "raw/amp_001_5t/amp_001_5t.sch"
    assert rel in decks
    assert decks[rel].startswith("v {xschem version=")  # the xschem header
    assert f"T {{{CIRCUIT}}}" in decks[rel]  # title block carries the circuit id
    assert export.sch_path(ota).name == "amp_001_5t.sch"  # one per circuit, not per pdk


def test_schematic_is_not_a_testbench_in_the_index():
    """The ``.sch`` lives in the tree (and is drift-guarded) but never appears as a testbench deck."""
    pytest.importorskip("spicexplorer_netlist2xschem")
    idx = export.deck_index([CIRCUIT])
    for pdk_tbs in idx[CIRCUIT].values():
        assert all(rel.endswith(".spice") for rel in pdk_tbs.values())
        assert not any(k.endswith(".sch") or k == "amp_001_5t" for k in pdk_tbs)


# ───────────────────────────── catalog integration ─────────────────────────────


def test_catalog_carries_raw_and_schematic_blocks():
    cat = json.loads(paths.catalog_path().read_text())
    e = next(c for c in cat["circuits"] if c["id"] == CIRCUIT)
    assert {"ihp-sg13g2", "sky130", "gf180mcu"} <= set(e["raw"])  # any further registered lane may add groups
    assert e["raw"]["sky130"]["noise"] == "raw/amp_001_5t/sky130/noise.spice"
    # schematics are reference-only pointers to files that exist (amp_001_5t has authored xschem)
    assert e["schematic"]["abstract"] == "circuits/amp_001_5t/abstract/schematic.svg"
    assert e["schematic"]["ihp-sg13g2"].endswith(".svg")


def test_catalog_raw_paths_all_exist_on_disk():
    cat = json.loads(paths.catalog_path().read_text())
    root = paths.db_root()
    for c in cat["circuits"]:
        for tbs in c.get("raw", {}).values():
            for rel in tbs.values():
                assert (root / rel).is_file(), f"catalog → missing {rel}"


def test_catalog_is_deterministic_with_raw_block():
    assert paths.catalog_path().read_text() == catalog.catalog_json()


# ───────────────────────────── the verify guards ─────────────────────────────


@pytest.mark.corpus
def test_committed_raw_tree_is_in_sync(generated_decks):
    """The drift guard: committed raw/ == a fresh render (no stale / missing / orphan)."""
    stale, missing, orphan = export.check_drift(decks=generated_decks)
    assert not stale and not missing and not orphan, (stale[:3], missing[:3], orphan[:3])


@pytest.mark.corpus
def test_verify_raw_tiers_are_green(tier0_results, tier1_results):
    t0 = {r.check: r for r in tier0_results}
    t1 = {r.check: r for r in tier1_results}
    assert t0["raw:catalog_xref"].status == "pass", t0["raw:catalog_xref"].reason
    assert t1["raw:drift"].status == "pass", t1["raw:drift"].reason
