"""The deterministic composer / flattener (plan_hierarchical_composition §5, P4-2).

A COMPOSITE circuit authors ``composition.yaml`` (``spicexplorer/composition@1``): an
instance list naming registry blocks by pinned id, a block-port→parent-net map, optional
``taps:`` (wire a parent net onto a block-INTERNAL node) + ``omit:`` (drop a block device
card the parent wiring replaces — the D3 "instantiator owns bias" seam), parent-owned
sizing ``override:``s, and composite-own ``nets:`` lines. The composer emits the
composite's ``abstract/netlist.spice`` as a FLAT, SELF-CONTAINED deck (the amp_023/AFE
shape that already lowers and verifies) plus a per-PDK ``sizing.yaml`` materialized from
the instance sizings — both GENERATED and byte-drift-guarded like every other generated
artifact (§5.3: sorted instances, stable renaming, block-netlist line order).

Renaming (deterministic, matches the corpus' hand-flatten precedent — sup_003's
``XM1_OPAMP`` suffixes):
  - device ``XM1`` in instance ``core``      → ``XM1_CORE``
  - block-internal net ``stg1p``             → ``core__stg1p`` (ports/taps map to parent nets)
  - mechanical symbol ``x_dut_xm1_w``        → ``x_dut_xm1_core_w``  (== atomic_symbol of the
    renamed device, so ``gen-params`` regenerates consistently)
  - free knob ``vbl`` / ``gm_val``           → ``vbl_core`` / ``gm_val_core``

The composer runs ABOVE circuitgraph (it only ever sees the flat result), so E1
hierarchical lowering is never needed. Blocks that are themselves composites compose
transitively through their committed (already-flat) ``abstract/netlist.spice``; the DAG
validator rejects cycles.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from . import model, params

COMPOSITION_FILE = "composition.yaml"

_GEN_NETLIST_HEADER = (
    "** GENERATED by `analog-db generate` — DO NOT EDIT. Source: composition.yaml (composer, plan P4)\n"
)
_GEN_SIZING_HEADER = (
    "# GENERATED by `analog-db generate` — DO NOT EDIT. Source: composition.yaml (composer, plan P4).\n"
    "# Materialized from the pinned blocks' pdk/<pdk>/sizing.yaml (symbols renamed per instance)\n"
    "# ⊕ the instances' parent-owned `override:`s ⊕ the composite's own `sizing:` variables.\n"
)

# SPICE source-card keywords that may appear bare in a value position and are NOT symbols.
_SPICE_KEYWORDS = frozenset(
    {"dc", "ac", "pulse", "sin", "sine", "pwl", "exp", "sffm", "am", "portnum", "trnoise"}
)

# device-type letter → count of net tokens after the name (X handled separately)
_NET_COUNTS = {"r": 2, "c": 2, "l": 2, "v": 2, "i": 2, "d": 2, "g": 4, "e": 4, "f": 2, "h": 2}

_INSTANCE_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
_IDENT_RE = re.compile(r"(?<![\w.])[A-Za-z_][A-Za-z0-9_]*")
_PIN_LEN = 12


class ComposeError(RuntimeError):
    """A composition that cannot be deterministically flattened."""


# ---------------------------------------------------------------- card parsing


@dataclass(frozen=True)
class Card:
    """One parsed device card: name + net tokens + everything after the nets."""

    name: str
    nets: tuple[str, ...]
    rest: tuple[str, ...]
    model_token: str | None = None  # X-cards only


def _parse_cards(netlist_text: str, where: str) -> list[Card]:
    """Device cards of an abstract netlist, in file order (comments/.end skipped)."""
    cards: list[Card] = []
    for ln, raw in enumerate(netlist_text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("*"):
            continue
        if line.startswith("."):
            if line.lower() in (".end", ".ends"):
                continue
            raise ComposeError(
                f"{where}:{ln}: directive {line.split()[0]!r} in an abstract netlist is not "
                "composable (only device cards + comments are)"
            )
        if line.startswith("+"):
            raise ComposeError(f"{where}:{ln}: continuation lines are not composable")
        toks = line.split()
        name = toks[0]
        kind = name[0].lower()
        if kind == "x":
            # nets … model, then k=v params: strip trailing k=v, the token before is the model
            body = toks[1:]
            n_kv = 0
            while n_kv < len(body) and "=" in body[len(body) - 1 - n_kv]:
                n_kv += 1
            if len(body) - n_kv < 2:
                raise ComposeError(f"{where}:{ln}: malformed X card {name!r}")
            cards.append(
                Card(
                    name=name,
                    nets=tuple(body[: len(body) - n_kv - 1]),
                    rest=tuple(body[len(body) - n_kv :]),
                    model_token=body[len(body) - n_kv - 1],
                )
            )
            continue
        n = _NET_COUNTS.get(kind)
        if n is None:
            raise ComposeError(f"{where}:{ln}: unsupported device type {name!r}")
        if len(toks) < 1 + n:
            raise ComposeError(f"{where}:{ln}: card {name!r} has fewer than {n} net tokens")
        cards.append(Card(name=name, nets=tuple(toks[1 : 1 + n]), rest=tuple(toks[1 + n :])))
    return cards


# ------------------------------------------------------------ renaming helpers


def rename_symbol(sym: str, inst: str) -> str:
    """Namespace one block-local free symbol into the parent (see the module header)."""
    if sym.startswith("x_dut_"):
        dev, _, fld = sym[len("x_dut_") :].rpartition("_")
        return f"x_dut_{dev}_{inst}_{fld}"
    return f"{sym}_{inst}"


def _rename_expr(text: str, inst: str) -> str:
    """Rename every free-symbol identifier inside a value expression ({…} / '…' contents)."""
    return _IDENT_RE.sub(lambda m: rename_symbol(m.group(0), inst), text)


def _rename_value_token(tok: str, inst: str) -> str:
    """One post-net token of a card: k=v param, braced/quoted expression, or bare symbol."""
    if "=" in tok:
        k, _, v = tok.partition("=")
        return f"{k}={_rename_value_token(v, inst)}"
    if tok.startswith("{") or tok.startswith("'"):
        return _rename_expr(tok, inst)
    if _IDENT_RE.fullmatch(tok) and tok.lower() not in _SPICE_KEYWORDS:
        return rename_symbol(tok, inst)
    return tok  # a number (10u, 2.5p), a keyword, or anything non-symbolic


def _render_card(card: Card, inst: str, net_map: dict[str, str]) -> str:
    name = f"{card.name}_{inst.upper()}"
    nets = [net_map.get(n, f"{inst}__{n}") for n in card.nets]
    rest = [_rename_value_token(t, inst) for t in card.rest]
    mid = [card.model_token] if card.model_token is not None else []
    return " ".join([name, *nets, *mid, *rest])


# --------------------------------------------------------------------- loading


@dataclass(frozen=True)
class Instance:
    name: str
    block: model.Circuit
    pin: str
    ports: dict[str, str]
    taps: dict[str, str] = field(default_factory=dict)
    omit: tuple[str, ...] = ()
    override: dict[str, Any] = field(default_factory=dict)


def composition_path(circuit: model.Circuit) -> Path:
    return circuit.dir / COMPOSITION_FILE


def is_composite(circuit: model.Circuit) -> bool:
    return composition_path(circuit).is_file()


def load_composition(circuit: model.Circuit) -> dict[str, Any]:
    with composition_path(circuit).open() as fh:
        doc = yaml.safe_load(fh)
    if not isinstance(doc, dict):
        raise ComposeError(f"{circuit.id}: composition.yaml is not a YAML mapping")
    return doc


def block_pin(block: model.Circuit) -> str:
    """The block's topology pin: sha256 of its committed cgraph JSON, first 12 hex chars."""
    cg = block.dir / "abstract" / "topology.cgraph.json"
    if not cg.is_file():
        raise ComposeError(
            f"block {block.id}: no committed topology.cgraph.json to pin "
            f"(run `analog-db generate --circuit {block.id}` first)"
        )
    return hashlib.sha256(cg.read_bytes()).hexdigest()[:_PIN_LEN]


def _instances(circuit: model.Circuit, doc: dict[str, Any]) -> list[Instance]:
    rows = doc.get("instances")
    if not isinstance(rows, list) or not rows:
        raise ComposeError(f"{circuit.id}: composition.yaml has no instances")
    out: list[Instance] = []
    for row in rows:
        out.append(
            Instance(
                name=str(row.get("name", "")),
                block=model.load_circuit(str(row.get("block", ""))),
                pin=str(row.get("pin", "")),
                ports={str(k): str(v) for k, v in (row.get("ports") or {}).items()},
                taps={str(k): str(v) for k, v in (row.get("taps") or {}).items()},
                omit=tuple(str(x) for x in (row.get("omit") or [])),
                override=dict(row.get("override") or {}),
            )
        )
    return sorted(out, key=lambda i: i.name)


# ------------------------------------------------------------------ validation


def validate(circuit: model.Circuit) -> list[str]:
    """P4-3 validators: interface, pins, taps/omit existence, acyclic DAG, PDK bindings,
    device-name collisions. Returns human-readable errors (empty = composable)."""
    errs: list[str] = []
    try:
        doc = load_composition(circuit)
    except (ComposeError, yaml.YAMLError) as exc:
        return [str(exc)]
    if doc.get("of") not in (None, circuit.id):
        errs.append(f"of: {doc.get('of')!r} != circuit id {circuit.id!r}")
    try:
        instances = _instances(circuit, doc)
    except (ComposeError, KeyError) as exc:
        return errs + [str(exc)]

    seen_names: set[str] = set()
    seen_devices: set[str] = set()
    for inst in instances:
        tag = f"instance {inst.name!r}"
        if not _INSTANCE_NAME_RE.match(inst.name):
            errs.append(f"{tag}: name must match {_INSTANCE_NAME_RE.pattern}")
        if inst.name in seen_names:
            errs.append(f"{tag}: duplicate instance name")
        seen_names.add(inst.name)
        # interface: EVERY block port mapped, nothing else
        want = set(inst.block.manifest.get("ports", []))
        have = set(inst.ports)
        if have != want:
            missing, extra = sorted(want - have), sorted(have - want)
            errs.append(f"{tag}: port map != block ports (missing {missing}, extra {extra})")
        # pin
        try:
            current = block_pin(inst.block)
            if inst.pin != current:
                errs.append(f"{tag}: pin {inst.pin!r} != block {inst.block.id}'s current {current!r}")
        except ComposeError as exc:
            errs.append(f"{tag}: {exc}")
        # taps + omit against the block netlist
        try:
            cards = _parse_cards(
                inst.block.abstract_netlist().read_text(), f"{inst.block.id}/abstract/netlist.spice"
            )
        except (ComposeError, FileNotFoundError) as exc:
            errs.append(f"{tag}: {exc}")
            continue
        block_nets = {n for c in cards for n in c.nets}
        block_devices = {c.name for c in cards}
        for net in inst.taps:
            if net not in block_nets:
                errs.append(f"{tag}: tap {net!r} names no net in {inst.block.id}'s netlist")
            elif net in want:
                errs.append(f"{tag}: tap {net!r} is a block PORT — map it via ports:, not taps:")
        for dev in inst.omit:
            if dev not in block_devices:
                errs.append(f"{tag}: omit {dev!r} names no device in {inst.block.id}'s netlist")
        for dev in block_devices:
            if dev in inst.omit:
                continue
            new = f"{dev}_{inst.name.upper()}"
            if new in seen_devices:
                errs.append(f"{tag}: renamed device {new!r} collides")
            seen_devices.add(new)
        # PDK bindings: the composite can only bind PDKs every block binds
        for pdk in circuit.pdks:
            if pdk not in inst.block.pdks:
                errs.append(f"{tag}: composite binds pdk {pdk!r} but block {inst.block.id} does not")
        # overrides must name symbols the block's sizing declares
        for pdk in circuit.pdks:
            if pdk not in inst.block.pdks:
                continue
            try:
                declared = {v.get("name") for v in inst.block.sizing(pdk).get("variables", [])}
            except FileNotFoundError as exc:
                errs.append(f"{tag}: {exc}")
                continue
            for sym in inst.override:
                if sym not in declared:
                    errs.append(f"{tag}: override {sym!r} not declared in {inst.block.id}'s {pdk} sizing")
    # composite nets: device names must not collide with renamed instance devices
    for line in doc.get("nets") or []:
        name = str(line).split()[0] if str(line).split() else ""
        if name in seen_devices:
            errs.append(f"nets: device {name!r} collides with an instance device")
        seen_devices.add(name)
    errs.extend(_dag_errors(circuit))
    return errs


def _dag_errors(circuit: model.Circuit, _stack: tuple[str, ...] = ()) -> list[str]:
    """Reject instance cycles (a composite that — transitively — instantiates itself)."""
    if circuit.id in _stack:
        return [f"composition cycle: {' -> '.join((*_stack, circuit.id))}"]
    if not is_composite(circuit):
        return []
    errs: list[str] = []
    try:
        doc = load_composition(circuit)
        for inst in _instances(circuit, doc):
            errs.extend(_dag_errors(inst.block, (*_stack, circuit.id)))
    except (ComposeError, KeyError) as exc:
        errs.append(str(exc))
    return errs


# -------------------------------------------------------------------- emission


def compose_netlist(circuit: model.Circuit) -> str:
    """The composite's flat, self-contained ``abstract/netlist.spice`` (deterministic)."""
    doc = load_composition(circuit)
    errs = validate(circuit)
    if errs:
        raise ComposeError(f"{circuit.id}: composition invalid: " + "; ".join(errs))
    instances = _instances(circuit, doc)

    lines: list[str] = [_GEN_NETLIST_HEADER.rstrip("\n")]
    parts = " + ".join(f"{i.name}({i.block.id} @ {i.pin})" for i in instances)
    lines.append(f"** Composite: {circuit.id} = {parts}")
    for note in str(doc.get("notes", "")).splitlines():
        if note.strip():
            lines.append(f"** {note.rstrip()}")
    ports = " ".join(circuit.manifest.get("ports", []))
    lines.append(f"**.subckt {circuit.id} {ports}")
    for inst in instances:
        lines.append(
            f"* --- instance {inst.name}: {inst.block.id} @ {inst.pin}"
            + (f" (omit: {', '.join(inst.omit)})" if inst.omit else "")
            + " ---"
        )
        cards = _parse_cards(
            inst.block.abstract_netlist().read_text(), f"{inst.block.id}/abstract/netlist.spice"
        )
        net_map = {**{k: v for k, v in inst.ports.items()}, **inst.taps, "0": "0"}
        for card in cards:
            if card.name in inst.omit:
                continue
            lines.append(_render_card(card, inst.name, net_map))
    nets = [str(x) for x in (doc.get("nets") or [])]
    if nets:
        lines.append("* --- composite-owned nets ---")
        lines.extend(nets)
    lines.append("**.ends")
    lines.append(".end")
    return "\n".join(lines) + "\n"


def _render_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return json.dumps(v)
    return json.dumps(str(v))


_ROW_KEY_ORDER = ("name", "description", "default", "min", "max", "unit", "freeze", "is_integer")


def _render_variable_row(row: dict[str, Any]) -> str:
    keys = [k for k in _ROW_KEY_ORDER if k in row] + sorted(set(row) - set(_ROW_KEY_ORDER))
    body = ", ".join(f"{k}: {_render_scalar(row[k])}" for k in keys)
    return f"  - {{{body}}}"


def _own_variables(doc: dict[str, Any], pdk: str) -> list[dict[str, Any]]:
    """The composite's OWN sizing rows for one PDK: ``sizing.variables`` with
    ``sizing.by_pdk[pdk]`` merged key-wise over the row of the same ``name`` (unknown
    names append). A composite-owned device is real geometry, and a block's sized W/L is
    per-PDK — one shared default would carry one kit's numbers into another."""
    sizing = doc.get("sizing") or {}
    own = [dict(v) for v in (sizing.get("variables") or [])]
    index = {v.get("name"): i for i, v in enumerate(own)}
    for var in (sizing.get("by_pdk") or {}).get(pdk) or []:
        name = var.get("name")
        if name in index:
            own[index[name]] = {**own[index[name]], **var}
        else:
            index[name] = len(own)
            own.append(dict(var))
    return own


def composite_tied_symbols(circuit: model.Circuit) -> set[str]:
    """Symbols the composite's AUTHORED ``abstract/params.yaml`` defines through a tie.

    Composition can create a tie that neither block had: e.g. the CMFB block sizes its tail
    XM1 and its bias diode XM3 independently, but in the composite the two are detected as a
    ``mirror_length`` pair, so ``..._xm1_..._l`` becomes a TIED FOLLOWER. A materialized sizing
    row for such a symbol would DOUBLE-DEFINE it in the generated ``_dut.spice`` (the later tie
    line wins), so the composer must not emit one — same reason a hand-authored circuit never
    writes a sizing row for a tied symbol (plan D-4; enforced by the Tier-1 ``params:sizing``
    check). Empty until the composite has adopted ``abstract/params.yaml``.
    """
    p = circuit.dir / "abstract" / "params.yaml"
    if not p.is_file():
        return set()
    with p.open() as fh:
        pdoc = yaml.safe_load(fh) or {}
    return params.tied_symbols(pdoc) if isinstance(pdoc, dict) else set()


def compose_sizing(circuit: model.Circuit, pdk: str, composed_netlist: str) -> str:
    """The composite's ``pdk/<pdk>/sizing.yaml``: block variables renamed per instance,
    parent ``override:``s applied to defaults, variables whose symbol no longer appears in
    the composed netlist — or is a TIED follower in the composite's params.yaml — dropped,
    then the composite's own ``sizing.variables`` appended, refined for this PDK by
    ``sizing.by_pdk[pdk]``."""
    doc = load_composition(circuit)
    instances = _instances(circuit, doc)
    tied = composite_tied_symbols(circuit)
    rows: list[str] = []
    for inst in instances:
        rows.append(f"  # -- instance {inst.name}: {inst.block.id} ({pdk}) --")
        for var in inst.block.sizing(pdk).get("variables", []):
            new = dict(var)
            new["name"] = rename_symbol(str(var.get("name", "")), inst.name)
            if var.get("name") in inst.override:
                new["default"] = inst.override[var["name"]]
            if new["name"] not in composed_netlist:
                continue  # its device/knob was omitted or replaced by parent wiring
            if new["name"] in tied:
                continue  # the composite's params.yaml tie already defines it (no shadow row)
            rows.append(_render_variable_row(new))
    own = [v for v in _own_variables(doc, pdk) if str(v.get("name", "")) not in tied]
    if own:
        rows.append("  # -- composite-owned knobs --")
        rows.extend(_render_variable_row(dict(v)) for v in own)
    # per-PDK testbench conditions (VDD/VCM where the kits' rails differ): the composite
    # is the instantiator, so it owns them — the blocks' own analysis_params describe the
    # blocks standalone and do not compose.
    conds = ((doc.get("sizing") or {}).get("analysis_params_by_pdk") or {}).get(pdk) or {}
    cond_block = ""
    if conds:
        cond_block = "analysis_params:\n" + "".join(
            f"  {k}: {_render_scalar(v) if isinstance(v, str) else v}\n" for k, v in conds.items()
        )
    return (
        _GEN_SIZING_HEADER
        + "schema: spicexplorer/sizing@1\n"
        + f"pdk: {pdk}\n"
        + cond_block
        + "variables:\n"
        + "\n".join(rows)
        + "\n"
    )


def composed_block_groups(circuit: model.Circuit) -> list[dict[str, Any]]:
    """The blocks' AUTHORED params.yaml ``groups:`` ported through the composer rename
    (§12.7 "matching composes through the prefix") — block ties are invariants of the
    block, so a fresh composite proposal should inherit them instead of relying on
    structural re-detection (which misses value ties and authored intent).

    Members are renamed ``<member>_<INST>``; members of omitted devices are dropped
    (a group left with fewer than two members is dropped whole)."""
    doc = load_composition(circuit)
    out: list[dict[str, Any]] = []
    for inst in _instances(circuit, doc):
        pfile = inst.block.dir / "abstract" / "params.yaml"
        if not pfile.is_file():
            continue
        with pfile.open() as fh:
            pdoc = yaml.safe_load(fh) or {}
        for g in pdoc.get("groups", []):
            members = [f"{m}_{inst.name.upper()}" for m in g.get("members", []) if m not in inst.omit]
            if len(members) < 2:
                continue
            ng = dict(g)
            ng["name"] = f"{g.get('name', 'group')}_{inst.name}"
            ng["members"] = members
            desc = str(g.get("description", "")).rstrip(". ")
            tail = f"(ported from {inst.block.id} through the composer rename)."
            ng["description"] = f"{desc} {tail}".strip() if desc else tail
            out.append(ng)
    return out


def merge_composed_groups(doc: dict[str, Any], circuit: model.Circuit) -> dict[str, Any]:
    """Merge the blocks' ported groups into a freshly PROPOSED composite params doc:
    block groups win over structural re-detections of the same member set (the block
    author's tie carries intent the detector can't)."""
    ported = composed_block_groups(circuit)
    taken = {frozenset(g["members"]) for g in ported}
    kept = [g for g in doc.get("groups", []) if frozenset(g.get("members", [])) not in taken]
    doc["groups"] = ported + kept
    return doc


def write_composed(circuit: model.Circuit) -> list[str]:
    """(Re)write the composite's generated inputs (flat netlist + per-PDK sizing).

    Returns the written paths relative to the circuit dir; [] for a non-composite."""
    if not is_composite(circuit):
        return []
    written: list[str] = []
    nl = circuit.dir / "abstract" / "netlist.spice"
    nl.parent.mkdir(parents=True, exist_ok=True)
    text = compose_netlist(circuit)
    nl.write_text(text)
    written.append("abstract/netlist.spice")
    for pdk in circuit.pdks:
        out = circuit.dir / "pdk" / pdk / "sizing.yaml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(compose_sizing(circuit, pdk, text))
        written.append(f"pdk/{pdk}/sizing.yaml")
    return written
