"""Materialize ready-to-run testbench decks under ``raw/``.

``assemble()`` already renders one ``(circuit × analysis × pdk × corner)`` cell into a complete,
self-contained netlist; this module **persists** those decks into a committed, drift-guarded tree so
an analog designer (or agent, or the UI) can pull one ``.spice`` and simulate it directly:

  ``raw/<circuit>/<pdk>/<analysis>[__<corner>].spice``  — one self-contained deck per testbench
  ``raw/<circuit>/<pdk>/_dut.spice``                    — standalone lowered DUT subckt
  ``raw/<circuit>/<circuit>.sch``                       — the DUT topology as an xschem schematic

(The tree is flat per circuit: the accession id's ``<code>_`` prefix already carries the class.)

GENERATED, never hand-edited: a fresh re-export must be **byte-identical** to the committed tree
(Tier-1 drift guard), so every deck is deterministic — no timestamps, no host paths (unlike
``scoreboard/`` entries, which carry ``run_at`` and are not byte-guarded). The corner ``.lib`` includes
resolve by bare name on the image's ngspice sourcepath, so a deck runs only in a PDK-enabled env (the
base image / api container), not a bare host — stated in each deck's banner.

The ``.sch`` is produced by ``spicexplorer-netlist2xschem`` (pure Python, deterministic, one per
circuit since topology is PDK-independent) and is drift-guarded like the decks; **rendering** it to an
``.svg``/``.png`` needs xschem and is a separate optional step (``export-raw --svg``, container only).
"""

from __future__ import annotations

from pathlib import Path

from . import model, paths
from .assemble import AssembleError, assemble, dut_subckt

# the in-flight failures that mean "this cell isn't exportable yet" (incomplete binding, missing
# sizing default, unbound PDK) — logged + skipped, never aborting the whole export.
_SKIP_EXC = (AssembleError, FileNotFoundError, KeyError, ValueError)

_RULE = "*----------------------------------------------------------*\n"
_RUN_IMAGE = "spicexplorer-spice-base:local"

# The reference PDK whose xschem symbols are vendored. A circuit's schematic is its topology, which is
# PDK-independent, so we emit one ``.sch`` per circuit (not per PDK) drawn from this PDK's lowered netlist.
_SCH_PDK = "ihp-sg13g2"


# --------------------------------------------------------------------------- paths


def raw_root() -> Path:
    return paths.db_root() / "raw"


def circuit_raw_dir(circuit: model.Circuit, pdk: str) -> Path:
    return raw_root() / circuit.id / pdk


def _deck_filename(analysis_id: str, corner: str) -> str:
    """``tt`` is implied by the bare name; other corners get a ``__<corner>`` suffix."""
    return f"{analysis_id}.spice" if corner == "tt" else f"{analysis_id}__{corner}.spice"


def deck_path(circuit: model.Circuit, analysis_id: str, pdk: str, corner: str = "tt") -> Path:
    return circuit_raw_dir(circuit, pdk) / _deck_filename(analysis_id, corner)


def dut_path(circuit: model.Circuit, pdk: str) -> Path:
    return circuit_raw_dir(circuit, pdk) / "_dut.spice"


def sch_path(circuit: model.Circuit) -> Path:
    """The circuit's xschem schematic — one per circuit (topology is PDK-independent), at circuit level."""
    return raw_root() / circuit.id / f"{circuit.id}.sch"


def annotated_sch_path(circuit: model.Circuit) -> Path:
    """The block-annotated topology schematic (detected functional blocks drawn as coloured boxes)."""
    return raw_root() / circuit.id / f"{circuit.id}_annotated.sch"


def structural_path(circuit: model.Circuit) -> Path:
    """The circuit's structural analysis (detected blocks + per-device roles) as JSON."""
    return raw_root() / circuit.id / f"{circuit.id}.structural.json"


def hier_dir(circuit: model.Circuit) -> Path:
    """Directory holding the hierarchical ("block diagram") schematic: a parent ``<id>.sch`` + ``blocks/``
    (one child ``.sch`` + generated ``.sym`` per detected block)."""
    return raw_root() / circuit.id / "hier"


def hier_parent_path(circuit: model.Circuit) -> Path:
    return hier_dir(circuit) / f"{circuit.id}.sch"


def _rel(path: Path) -> str:
    return str(path.relative_to(paths.db_root()))


# --------------------------------------------------------------------------- banners (deterministic)


def _deck_banner(circuit: model.Circuit, analysis_id: str, pdk: str, corner: str, rel: str) -> str:
    return (
        "** GENERATED by `analog-db export-raw` — DO NOT EDIT.\n"
        f"** circuit={circuit.id}  class={circuit.klass}  pdk={pdk}  testbench={analysis_id}  corner={corner}\n"
        f"** Self-contained deck: testbench + bound params + lowered DUT (.subckt {circuit.id}).\n"
        "** PDK corner libs resolve by BARE NAME on the image's ngspice sourcepath — run in a\n"
        "** PDK-enabled env (the base image / api container), NOT a bare host:\n"
        f"**   docker run --rm -i {_RUN_IMAGE} \\\n"
        f"**     bash -lc 'd=$(mktemp -d) && cat > $d/c.spice && cd $d && ngspice -b c.spice' < {rel}\n"
        + _RULE
    )


def _dut_banner(circuit: model.Circuit, pdk: str) -> str:
    ports = " ".join(circuit.manifest.get("ports", []))
    return (
        "** GENERATED by `analog-db export-raw` — DO NOT EDIT.\n"
        f"** Standalone lowered DUT subckt for {circuit.id} on {pdk} "
        "(sizing .param defaults + .subckt).\n"
        "** Not a runnable deck on its own — include it under your own testbench:\n"
        "**   .include _dut.spice\n"
        f"**   XDUT {ports} {circuit.id}\n"
        f"** Source: pdk/{pdk}/netlist.spice (run `analog-db generate` to refresh).\n" + _RULE
    )


# --------------------------------------------------------------------------- rendering


def render_deck(circuit: model.Circuit, analysis_id: str, pdk: str, corner: str = "tt") -> str:
    """A committed-deck = ``assemble()`` with its one-line provenance header swapped for the
    structured DO-NOT-EDIT banner (the netlist body is byte-for-byte the assembler's output)."""
    deck = assemble(circuit, analysis_id, pdk, corner)
    _, _, body = deck.partition("\n")  # drop assemble's `** ASSEMBLED …` first line
    rel = _rel(deck_path(circuit, analysis_id, pdk, corner))
    return _deck_banner(circuit, analysis_id, pdk, corner, rel) + _params_line(circuit, pdk, body) + body


def _params_line(circuit: model.Circuit, pdk: str, body: str, tb: bool = True) -> str:
    """Provenance-count banner line for an analysis deck: the DUT classes plus
    how many ``.param`` names are TESTBENCH-side (defined in the deck but outside the DUT's
    sizing/tie surface). Empty — deck byte-identical — without ``abstract/params.yaml``."""
    import re as _re

    from .params import classify_symbols, counts_line, load_params_doc

    doc = load_params_doc(circuit.dir)
    if not doc:
        return ""
    cls = classify_symbols(doc, circuit.sizing(pdk).get("variables", []))
    tb_params = None
    if tb:
        dut_syms = {sym for syms in cls.values() for sym in syms}
        deck_params = set(_re.findall(r"^\.param\s+(\S+?)\s*=", body, _re.M))
        tb_params = len(deck_params - dut_syms)
    return f"** params: {counts_line(cls, tb_params=tb_params)}\n"


def render_dut(circuit: model.Circuit, pdk: str) -> str:
    body = dut_subckt(circuit, pdk)
    return _dut_banner(circuit, pdk) + _params_line(circuit, pdk, body, tb=False) + body


def _n2x_circuit(circuit: model.Circuit):
    """The DUT as a ``netlist2xschem`` circuit: wrap the lowered ``.subckt`` in a one-line ``XDUT``
    instance and descend into it, so the schematic shows the DUT's own devices."""
    from spicexplorer_netlist2xschem import from_string

    ports = " ".join(circuit.manifest["ports"])
    deck = dut_subckt(circuit, _SCH_PDK) + f"XDUT {ports} {circuit.id}\n.end\n"
    return from_string(deck, name=circuit.id, into="XDUT")


def _dut_graph(circuit: model.Circuit):
    """A ``circuitgraph`` graph of the circuit's PDK-neutral **abstract** netlist, with functional
    sub-circuits detected and per-device structural roles assigned (``annotate_subcircuits`` mutates the
    graph). Shared by the annotated schematic, the hierarchy and the structural JSON so all three agree
    on one detection. Detection is PDK-independent (topology only), so the abstract netlist is the right
    source; its instance refs (``XM*``) join to the schematic devices by name."""
    from spicexplorer_circuitgraph import CircuitGraph, annotate_subcircuits
    from spicexplorer_core.spice_engine import NetlistView

    graph = CircuitGraph.from_netlist(
        NetlistView.from_file(circuit.abstract_netlist()), name=circuit.id
    )
    groups = annotate_subcircuits(graph)
    return graph, groups


def _annotation_set(groups):
    """The detected ``groups`` as a ``netlist2xschem`` ``BlockAnnotationSet`` (the rendering contract)."""
    from spicexplorer_circuitgraph.annotations import export_subcircuit_annotations
    from spicexplorer_netlist2xschem import BlockAnnotationSet

    return BlockAnnotationSet.from_dict(export_subcircuit_annotations(groups))


def render_sch(circuit: model.Circuit) -> str:
    """The DUT's topology as a plain xschem ``.sch`` (deterministic text) via ``netlist2xschem``.

    Pure Python — no xschem binary needed (that is only for rendering the ``.sch`` to SVG/PNG, a separate
    optional step). Raises ``ImportError`` when the optional tool isn't installed and ``_SKIP_EXC`` when
    the DUT won't assemble — both handled by ``_generate_circuit``.
    """
    from spicexplorer_netlist2xschem import to_sch

    return to_sch(_n2x_circuit(circuit), pdk=_SCH_PDK, title=circuit.id)


def render_annotated_sch(circuit: model.Circuit, aset) -> str:
    """The block-annotated topology ``.sch``: the detected functional blocks (current mirrors, diff
    pairs, cascodes) drawn as coloured boxes over a block-aware placement of the same devices."""
    from spicexplorer_netlist2xschem import build_sch

    return build_sch(
        _n2x_circuit(circuit), pdk=_SCH_PDK, title=circuit.id,
        annotations=aset, placement_mode="block-aware",
    ).text


def render_hier_files(circuit: model.Circuit, aset) -> dict[str, str]:
    """The hierarchical ("block diagram") schematic as ``{repo-relative path: text}``: a parent
    ``hier/<id>.sch`` instantiating one symbol per block, plus ``hier/blocks/<block>.{sch,sym}``."""
    from spicexplorer_netlist2xschem import build_hierarchical_sch

    res = build_hierarchical_sch(_n2x_circuit(circuit), aset, pdk=_SCH_PDK, title=circuit.id)
    d = hier_dir(circuit)
    out = {_rel(d / f"{circuit.id}.sch"): res.parent_text}
    for fname, text in res.children.items():
        out[_rel(d / "blocks" / fname)] = text
    for fname, text in res.symbols.items():
        out[_rel(d / "blocks" / fname)] = text
    return out


def render_structural(circuit: model.Circuit, graph, groups) -> str:
    """The circuit's structural analysis as pretty JSON: a summary (device count, blocks detected,
    by-family counts, per-device structural roles) plus the detected groups (template, ports, devices)."""
    import json
    from collections import Counter

    roles = {
        c.name: c.structural_role.value
        for c in sorted(graph.get_components(), key=lambda c: c.name)
        if getattr(c, "structural_role", None) is not None
    }
    payload = {
        "schema": "spicexplorer/xschem-block-annotations@1",
        "circuit": circuit.id,
        "source_netlist": "abstract/netlist.spice",
        "summary": {
            "device_count": len(graph.get_components()),
            "blocks_detected": len(groups),
            "by_family": dict(Counter(g.family for g in groups)),
            "structural_roles": roles,
        },
        "groups": [
            {
                "group_id": g.group_id,
                "family": g.family,
                "mirror_class": g.mirror_class,
                "polarity": g.polarity,
                "template_id": g.template_id,
                "reference_device": g.reference_device,
                "output_devices": list(g.output_devices),
                "devices": list(g.devices),
                "ports": g.ports,
            }
            for g in groups
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


# --------------------------------------------------------------------------- pure generator


def _exportable_analyses(circuit: model.Circuit) -> tuple[list[str], list[tuple[str, str]]]:
    """The analyses that should produce a deck, plus the skipped (id, reason) — mirrors the
    runner's gating (missing binding file / ``enabled: false``)."""
    keep: list[str] = []
    skipped: list[tuple[str, str]] = []
    for aid in circuit.analyses:
        apath = circuit.dir / "analyses" / f"{aid}.yaml"
        if not apath.is_file():
            skipped.append((f"{circuit.id}/{aid}", f"analyses/{aid}.yaml missing"))
        elif not circuit.analysis(aid).get("enabled", True):
            skipped.append((f"{circuit.id}/{aid}", "disabled"))
        else:
            keep.append(aid)
    return keep, skipped


def _generate_circuit(
    circuit: model.Circuit, corners: tuple[str, ...], pdks: list[str] | None
) -> tuple[dict[str, str], list[tuple[str, str]]]:
    """Pure: ``({repo-relative path: deck text}, skipped)`` for one circuit. No filesystem writes."""
    decks: dict[str, str] = {}
    analyses, skipped = _exportable_analyses(circuit)
    targets = [p for p in circuit.pdks if pdks is None or p in pdks]
    for pdk in targets:
        # the standalone DUT doubles as the binding canary: if it won't assemble, every deck on this
        # PDK would fail the same way (they embed it) — skip the whole PDK with one reason.
        try:
            decks[_rel(dut_path(circuit, pdk))] = render_dut(circuit, pdk)
        except _SKIP_EXC as exc:
            skipped.append((f"{circuit.id}@{pdk}", f"DUT unavailable: {type(exc).__name__}: {exc}"))
            continue
        for aid in analyses:
            for corner in corners:
                try:
                    text = render_deck(circuit, aid, pdk, corner)
                except _SKIP_EXC as exc:
                    skipped.append((f"{circuit.id}/{aid}@{pdk}/{corner}", str(exc)))
                    continue
                decks[_rel(deck_path(circuit, aid, pdk, corner))] = text

    # Schematics per circuit, from the reference PDK. Best-effort and additive: a missing optional tool
    # or an un-drawable DUT is skipped with a reason, never aborting the deck export. Three views:
    #   <id>.sch            — the plain topology;
    #   <id>_annotated.sch  — the detected functional blocks as coloured boxes (block-aware placement);
    #   hier/<id>.sch + blocks/  — the hierarchical "block diagram" (one subcircuit symbol per block);
    #   <id>.structural.json — the detection itself (blocks, ports, per-device roles).
    # The last three share one circuitgraph detection, so a detector hiccup skips them together.
    if _SCH_PDK in targets:
        try:
            decks[_rel(sch_path(circuit))] = render_sch(circuit)
        except ImportError:
            skipped.append((f"{circuit.id}.sch", "spicexplorer-netlist2xschem not installed"))
        except _SKIP_EXC as exc:
            skipped.append((f"{circuit.id}.sch", f"schematic: {type(exc).__name__}: {exc}"))
        try:
            graph, groups = _dut_graph(circuit)
            aset = _annotation_set(groups)
            decks[_rel(annotated_sch_path(circuit))] = render_annotated_sch(circuit, aset)
            decks[_rel(structural_path(circuit))] = render_structural(circuit, graph, groups)
            decks.update(render_hier_files(circuit, aset))
        except ImportError:
            skipped.append((f"{circuit.id} structural/annotated", "circuitgraph/netlist2xschem absent"))
        except _SKIP_EXC as exc:
            skipped.append((f"{circuit.id} structural/annotated", f"{type(exc).__name__}: {exc}"))
    return decks, skipped


# One full-corpus render is ~tens of seconds (assembly + subcircuit detection + xschem drawing
# for every circuit) and several entry points need it — catalog_json/deck_index (via the Tier-0
# xref), the drift guard, write_all. Within one process the committed sources don't change, so
# the full-render result is memoized per db_root. Anything that edits circuit sources in-process
# and re-renders under the SAME root must pass use_cache=False (the determinism test does, so it
# keeps exercising a genuinely fresh render).
_full_render_cache: dict[tuple, tuple[dict[str, str], list[tuple[str, str]]]] = {}


def generate_all(
    circuit_ids: list[str] | None = None,
    corners: tuple[str, ...] = ("tt",),
    pdks: list[str] | None = None,
    use_cache: bool = True,
) -> tuple[dict[str, str], list[tuple[str, str]]]:
    """Pure render of the whole (or a filtered) ``raw/`` tree — the single generator behind writing,
    the catalog ``raw`` block, and the drift guard. The unfiltered full render is memoized
    in-process per db_root (see ``_full_render_cache`` above); pass ``use_cache=False`` to force a
    fresh render."""
    key = (str(paths.db_root()), corners, None if pdks is None else tuple(pdks))
    if use_cache and circuit_ids is None:
        hit = _full_render_cache.get(key)
        if hit is not None:
            return dict(hit[0]), list(hit[1])
    decks: dict[str, str] = {}
    skipped: list[tuple[str, str]] = []
    for cid in circuit_ids if circuit_ids is not None else model.list_circuit_ids():
        d, s = _generate_circuit(model.load_circuit(cid), corners, pdks)
        decks.update(d)
        skipped.extend(s)
    if circuit_ids is None:
        _full_render_cache[key] = (decks, skipped)
        return dict(decks), list(skipped)
    return decks, skipped


# --------------------------------------------------------------------------- write / index / drift


def write_all(
    circuit_ids: list[str] | None = None,
    corners: tuple[str, ...] = ("tt",),
    pdks: list[str] | None = None,
) -> tuple[list[str], list[tuple[str, str]]]:
    """Materialize ``raw/`` to disk; return ``(written rel-paths, skipped)``."""
    decks, skipped = generate_all(circuit_ids, corners, pdks)
    root = paths.db_root()
    for rel, text in decks.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    return sorted(decks), skipped


def render_svgs(circuit_ids: list[str] | None = None) -> tuple[list[str], bool]:
    """Render committed ``.sch`` files to ``.svg`` beside them (an optional, NOT byte-guarded step).

    Needs the ``xschem`` binary (the base image / api container); on a host without it this is a clean
    no-op. Returns ``(rendered rel-paths, xschem_available)``. SVG bytes depend on the xschem/cairo
    version, so the ``.svg`` is deliberately kept out of the deterministic drift guard.
    """
    import os

    from spicexplorer_netlist2xschem import render, xschem_available
    from spicexplorer_netlist2xschem.sym_library import default_search_paths

    if not xschem_available():
        return [], False
    rendered: list[str] = []
    ids = circuit_ids if circuit_ids is not None else model.list_circuit_ids()
    for cid in ids:
        circuit = model.load_circuit(cid)
        # plain + annotated render against the default symbol path; the hierarchy parent additionally
        # needs its own ``hier/`` dir on the path so the generated ``blocks/*.sym`` resolve.
        targets: list[tuple[Path, str | None]] = [
            (sch_path(circuit), None),
            (annotated_sch_path(circuit), None),
            (
                hier_parent_path(circuit),
                os.pathsep.join([*(str(p) for p in default_search_paths()), str(hier_dir(circuit))]),
            ),
        ]
        for sch, lib in targets:
            if not sch.is_file():
                continue
            result = render(sch, fmt="svg", outdir=sch.parent, library_path=lib)
            if result.image_path is not None:
                rendered.append(_rel(result.image_path))
            (sch.parent / "xschemrc").unlink(missing_ok=True)  # render() drops a transient rc — tidy it
    return sorted(rendered), True


def deck_index(
    circuit_ids: list[str] | None = None, corners: tuple[str, ...] = ("tt",)
) -> dict[str, dict[str, dict[str, str]]]:
    """``{circuit_id: {pdk: {testbench: relpath}}}`` — the catalog's ``raw`` block, built from the
    same generator so the index can never disagree with the tree."""
    decks, _ = generate_all(circuit_ids, corners)
    index: dict[str, dict[str, dict[str, str]]] = {}
    for rel in decks:
        if not rel.endswith(".spice"):
            continue  # schematics (circuit-level <id>.sch) live in the tree but aren't testbench decks
        # raw/<circuit>/<pdk>/<name>.spice
        _, cid, pdk, fname = Path(rel).parts
        tb = fname[: -len(".spice")]
        index.setdefault(cid, {}).setdefault(pdk, {})[tb] = rel
    return index


def check_drift(
    circuit_ids: list[str] | None = None,
    corners: tuple[str, ...] = ("tt",),
    decks: dict[str, str] | None = None,
) -> tuple[list[str], list[str], list[str]]:
    """Compare the committed ``raw/`` tree against a fresh render.

    Returns ``(stale, missing, orphan)`` repo-relative paths: *stale* = committed bytes differ,
    *missing* = expected but absent, *orphan* = committed but not expected (only meaningful for a
    full-DB check, so it's skipped when ``circuit_ids`` is given). Pass an already-rendered
    ``decks`` mapping (from :func:`generate_all` with the same filters) to skip the re-render.
    """
    if decks is None:
        decks, _ = generate_all(circuit_ids, corners)
    root = paths.db_root()
    stale, missing = [], []
    for rel, text in decks.items():
        p = root / rel
        if not p.is_file():
            missing.append(rel)
        elif p.read_text() != text:
            stale.append(rel)
    orphan: list[str] = []
    if circuit_ids is None:
        rd = raw_root()
        # Guard every generated text artifact: decks (.spice), schematics (.sch), generated block
        # symbols (.sym) and the structural analysis (.structural.json). Rendered .svg is intentionally
        # excluded (its bytes track the xschem/cairo version, so it isn't byte-deterministic). Top-level
        # ``raw/_*`` dirs hold hand-curated research/demo artifacts (e.g. ``_block_placement_strategies``),
        # not harness output, so they are not subject to the orphan check.
        patterns = ("*.spice", "*.sch", "*.sym", "*.structural.json")
        on_disk = (
            {
                _rel(p)
                for pat in patterns
                for p in rd.rglob(pat)
                if not p.relative_to(rd).parts[0].startswith("_")
            }
            if rd.is_dir()
            else set()
        )
        orphan = sorted(on_disk - set(decks))
    return sorted(stale), sorted(missing), orphan
