"""Generators for the committed-but-derived artifacts.

``abstract/netlist.spice`` is AUTHORED; everything here is GENERATED from it:
  - ``abstract/topology.cgraph.json`` — circuitgraph serialization (the abstract source of truth).
  - ``pdk/<pdk>/netlist.spice`` — the abstract graph lowered to a PDK via ``to_netlist(pdk=…)``.

These are committed and CI-guarded: Tier 1 re-runs the generator and diffs the
committed file, so a stale commit fails.
"""

from __future__ import annotations

import json

from spicexplorer_circuitgraph import (
    CircuitGraph,
    CircuitGraphDoc,
    to_netlist,
)
from spicexplorer_core.spice_engine import NetlistView

from .model import Circuit
from .pdks import load_pdk

_GEN_HEADER = "** GENERATED by `analog-db generate` — DO NOT EDIT. Source: {src}\n"


def _abstract_graph(circuit: Circuit) -> CircuitGraph:
    nl = circuit.dir / "abstract" / "netlist.spice"
    return CircuitGraph.from_netlist(NetlistView.from_file(str(nl)), name=circuit.id)


def cgraph_json(circuit: Circuit) -> str:
    """Deterministic JSON of the abstract circuit graph."""
    doc = CircuitGraphDoc.from_graph(_abstract_graph(circuit))
    return json.dumps(doc.model_dump(), indent=2, sort_keys=True) + "\n"


def lowered_netlist(circuit: Circuit, pdk_name: str) -> str:
    """The abstract graph lowered to ``pdk_name`` (device names retargeted).

    Honors the per-topology ``pdk/<pdk>/devices.map.yaml`` override over the
    circuitgraph built-in table.
    """
    pdk = load_pdk(circuit, pdk_name)
    body = to_netlist(_abstract_graph(circuit), pdk=pdk, title=circuit.id)
    return _GEN_HEADER.format(src=f"abstract/netlist.spice → {pdk_name}") + body


def write_generated(circuit: Circuit) -> list[str]:
    """(Re)write all generated artifacts for one circuit; return the relative paths written.

    A ``kind: reference`` circuit has no abstract netlist to lower and no open-PDK bindings,
    so there is nothing to generate — return empty.
    """
    from . import compose
    from .extends import write_project_setup

    if circuit.is_reference_only:
        return []

    # composites first: composition.yaml → flat abstract/netlist.spice +
    # per-PDK sizing.yaml, so the ordinary pipeline below lowers the fresh compose.
    written: list[str] = list(compose.write_composed(circuit))
    cg = circuit.dir / "abstract" / "topology.cgraph.json"
    cg.write_text(cgraph_json(circuit))
    written.append(str(cg.relative_to(circuit.dir)))
    for pdk_name in circuit.pdks:
        out = circuit.dir / "pdk" / pdk_name / "netlist.spice"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(lowered_netlist(circuit, pdk_name))
        written.append(str(out.relative_to(circuit.dir)))
    ps = write_project_setup(circuit.dir)
    if ps is not None:
        written.append(str(ps.relative_to(circuit.dir)))
    return written
