"""Render a generated ``.sch`` to an image with headless xschem.

Verified behaviour in the EDA container (``spicexplorer-spice-base:local``):

* ``xschem -x -q --svg --plotfile <out.svg> <in.sch>`` renders **headlessly** via cairo and exits 0.
  Symbol resolution needs the PDK xschem dir on ``XSCHEM_LIBRARY_PATH`` (the container default omits
  it). We judge success by "a non-empty SVG was written", not by the exit code, because a benign
  ``tkwait`` message can appear on stderr. With net colouring on (the default), we instead drive the
  export through ``--command 'xschem select_all; xschem hilight; xschem print svg <out>'`` so the
  per-net highlight palette is applied first (``--svg`` exports before ``--command`` runs).
* ``xschem --png`` requires a running X server (it rasters through Tk), which the headless image lacks.
  So PNG is produced by rasterizing the SVG with :mod:`cairosvg` — no X server, and faithful to
  xschem's own rendering. ``cairosvg`` is an optional dependency (the ``[render]`` extra); when it's
  absent and PNG is requested, we return the SVG with a note.

When xschem isn't on ``PATH`` at all (e.g. a native macOS dev box), :func:`render` is a clean no-op:
it returns ``available=False`` with no image — the ``.sch`` itself is still valid and renders in the
UI's live viewer. PNG/SVG export is strictly additive.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .sym_library import default_search_paths

__all__ = ["RenderResult", "render", "xschem_available"]

ImageFmt = Literal["svg", "png"]


@dataclass(frozen=True)
class RenderResult:
    """The outcome of a render attempt."""

    sch_path: Path
    image_path: Path | None  # None when no image was produced
    fmt: ImageFmt | None
    available: bool  # was xschem on PATH?
    log: str = ""


def xschem_available() -> bool:
    """True if the ``xschem`` binary is on ``PATH``."""
    return shutil.which("xschem") is not None


def _library_path(explicit: str | None) -> str:
    if explicit:
        return explicit
    return os.pathsep.join(str(p) for p in default_search_paths())


def _rcfile_text(library_path: str) -> str:
    """An xschemrc that seeds the Tcl ``XSCHEM_LIBRARY_PATH`` from ``library_path``.

    xschem resolves symbols from the *Tcl* variable, which the stock system xschemrc leaves unset and
    which the ``XSCHEM_LIBRARY_PATH`` env var alone does not populate — and the seeding rc only loads
    from ``$HOME/.xschem`` (image- and HOME-dependent). Shipping our own rc and passing ``--rcfile``
    makes symbol resolution independent of the runtime image / HOME.
    """
    lines = ["# auto-generated by spicexplorer-netlist2xschem", "set XSCHEM_LIBRARY_PATH {}"]
    for entry in library_path.split(os.pathsep):
        if entry:
            lines.append("append XSCHEM_LIBRARY_PATH {:" + entry + "}")
    return "\n".join(lines) + "\n"


def write_xschemrc(directory: str | Path, library_path: str) -> Path:
    """Write an xschemrc seeding ``library_path`` into ``directory`` and return its path."""
    rc = Path(directory) / "xschemrc"
    rc.write_text(_rcfile_text(library_path))
    return rc


def _export_svg(sch_path: Path, svg_path: Path, library_path: str, color_nets: bool = True) -> str:
    rc = write_xschemrc(svg_path.parent, library_path)
    env = os.environ.copy()
    env["XSCHEM_LIBRARY_PATH"] = library_path  # belt-and-suspenders alongside the rcfile
    cmd = ["xschem", "--rcfile", str(rc), "-x", "-q"]
    if color_nets:
        # Give every net its own colour (xschem's incrementing highlight palette) so each net name and
        # its wires render in a matching colour — the same flag drawn twice is then obviously one node.
        # Done purely at render time (select-all → highlight → export), so the .sch stays unchanged.
        # ``print svg`` replaces the ``--svg``/``--plotfile`` flags, which export before --command runs.
        cmd += [
            "--command",
            f"set incr_hilight 1; xschem select_all; xschem hilight; xschem print svg {{{svg_path}}}",
        ]
    else:
        cmd += ["--svg", "--plotfile", str(svg_path)]
    cmd.append(str(sch_path))
    try:
        proc = subprocess.run(
            cmd, env=env, capture_output=True, text=True, timeout=120, cwd=str(svg_path.parent)
        )
        # Success is judged by the artifact, not the exit code (benign tkwait noise on stderr).
        return (proc.stdout or "") + (proc.stderr or "")
    except subprocess.TimeoutExpired:
        return "xschem --svg timed out after 120s"


def render(
    sch_path: str | Path,
    *,
    fmt: ImageFmt = "svg",
    outdir: str | Path | None = None,
    library_path: str | None = None,
    png_width: int = 1600,
    color_nets: bool = True,
) -> RenderResult:
    """Render ``sch_path`` to ``fmt`` (``"svg"`` or ``"png"``).

    Returns a :class:`RenderResult`. Degrades gracefully: no xschem → ``available=False`` (no image);
    PNG requested but no rasterizer → SVG returned with a note. The ``.sch`` is never modified.

    ``color_nets`` (default on) colour-codes the render: each net's name labels and wires share one
    colour from xschem's highlight palette, so the (often several) flags of one net read as one node.
    """
    sch_path = Path(sch_path)
    out = Path(outdir) if outdir is not None else sch_path.parent
    out.mkdir(parents=True, exist_ok=True)

    if not xschem_available():
        return RenderResult(
            sch_path,
            None,
            None,
            available=False,
            log="xschem not on PATH; the .sch is still valid for the UI's live viewer.",
        )

    svg_path = out / f"{sch_path.stem}.svg"
    log = _export_svg(sch_path, svg_path, _library_path(library_path), color_nets=color_nets)
    if not (svg_path.is_file() and svg_path.stat().st_size > 0):
        return RenderResult(
            sch_path, None, None, available=True, log=f"xschem produced no SVG:\n{log}"
        )

    if fmt == "svg":
        return RenderResult(sch_path, svg_path, "svg", available=True, log=log)

    # fmt == "png": rasterize the SVG (cairosvg; optional dependency).
    png_path = out / f"{sch_path.stem}.png"
    try:
        import cairosvg  # type: ignore[import-not-found]  # optional [render] extra, imported lazily

        cairosvg.svg2png(url=str(svg_path), write_to=str(png_path), output_width=png_width)
        return RenderResult(sch_path, png_path, "png", available=True, log=log)
    except Exception as exc:  # cairosvg missing or rasterization failed
        return RenderResult(
            sch_path,
            svg_path,
            "svg",
            available=True,
            log=f"{log}\nPNG requested but rasterization unavailable ({exc!r}); returning SVG instead.",
        )
